### ISSUE TITLE
Download Script Issues

### ISSUE THREAD

**Issue by neighthan** [hiwonjoon/cycle-gan-tf#1]
I wasn't unable to run your download script out of the box and had to change a couple of things. I'm not sure if you're using a different distribution where these might not happen? For reference, in case you want to change the script, I had errors with these lines:

```
TARGET_DIR=./datasets/$FILE/
mkdir $TARGET_DIR
```
The directory `./datasets` is not included in the repo, so this command fails because it can't make `./datasets/$FILE/` without `./datasets` already existing. You could either add `./datasets` to the repo as an empty directory or, as I did, change the line to

```
mkdir -p $TARGET_DIR
```

which lets it create any intermediate directories as well (and not throw an error if the directory _does_ already exist).

My second issue was with this line:

```
wget -N $URL -O $ZIP_FILE
````

From [the GNU manual on wget](https://www.gnu.org/software/wget/manual/wget.html), we see that -N and -O are not supported together. At least, it didn't work on my distro. I changed the line to

```
wget $URL -O $ZIP_FILE
````

and everything worked fine.

Thanks for the Tensorflow implementation, and I hope that this helps (I would have submitted a PR, but for just changing two flags, it seemed easier to let you decide if you want to make the change and do it yourself).

**Comment by hiwonjoon** [comment]
Thanks for such a detailed comments. As a specified on README, the script is brought from the original implementation by the author. Anyway, I will correct them as you specified. Thanks!
